name: Automated Heroku Deployment

on: 
  workflow_call

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "expressjs-demo-2022"
          heroku_email: "alex.holder@bigfootds.com"